class Config:
    SECRET_KEY = 'devykey123'
    SQLALCHEMY_DATABASE_URI = 'sqlite:///users.db'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    DEBUG = True
    TESTING = True

    WTF_CSRF_ENABLED = True

    RECAPTCHA_PUBLIC_KEY = 'publickey'
    RECAPTCHA_PRIVATE_KEY = 'privatekey'

    #Generated By ChatGPT

    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'    
    SESSION_COOKIE_SECURE = False       
    REMEMBER_COOKIE_HTTPONLY = True
    REMEMBER_COOKIE_SAMESITE = 'Lax'
    REMEMBER_COOKIE_SECURE = False      
