import os
import secrets


class Config:
    # Security (os.environ Generated By Copilot)
    SECRET_KEY = os.environ.get('SECRET_KEY') or secrets.token_hex(32)

    # Database
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL', 'sqlite:///users.db')
    SQLALCHEMY_TRACK_MODIFICATIONS = False

    # Runtime
    DEBUG = False
    TESTING = False

    # CSRF
    WTF_CSRF_ENABLED = True

    # Bcrypt Copilot
    BCRYPT_LOG_ROUNDS = 12  

    # reCAPTCHA (os.environ Generated By Copilot)
    RECAPTCHA_PUBLIC_KEY = os.environ.get('RECAPTCHA_PUBLIC_KEY')
    RECAPTCHA_PRIVATE_KEY = os.environ.get('RECAPTCHA_PRIVATE_KEY')

    # Cookies And Session
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SECURE = True
    REMEMBER_COOKIE_HTTPONLY = True
    REMEMBER_COOKIE_SAMESITE = 'Lax'
    REMEMBER_COOKIE_SECURE = True

    # Prefer HTTPS URLs
    PREFERRED_URL_SCHEME = 'https'
