from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_wtf import CSRFProtect
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from config import Config
import logging
from logging.handlers import RotatingFileHandler
import time
import os
from werkzeug.middleware.proxy_fix import ProxyFix

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s %(levelname)s %(message)s',
    datefmt='%Y-%m-%dT%H:%M:%SZ'
)
logging.Formatter.converter = time.gmtime  

db = SQLAlchemy()
login = LoginManager()
csrf = CSRFProtect()
limiter = Limiter(key_func=get_remote_address)

login.login_view = 'main.login'

def createApp():
    app = Flask(__name__)
    app.config.from_object(Config)

    # Generated By Copilot
    app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1, x_port=1)

    if not os.path.exists('logs'): # Generated By Copilot
        os.mkdir('logs')
    fileHandler = RotatingFileHandler('logs/auth.log', maxBytes=1_000_000, backupCount=5)
    fileHandler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s %(message)s',
        datefmt='%Y-%m-%dT%H:%M:%SZ'
    ))
    fileHandler.setLevel(logging.INFO)
    app.logger.addHandler(fileHandler)
    app.logger.setLevel(logging.INFO)
    app.logger.info('Application Startup')

    db.init_app(app)
    csrf.init_app(app)
    login.init_app(app)
    limiter.init_app(app)

    login.login_view = 'main.login'
    login.session_protection = "strong"

    from .routes import main
    app.register_blueprint(main)

    from .models import User

    @login.user_loader
    def loadUser(userId):
        return User.query.get(int(userId))

    return app