from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_wtf import CSRFProtect
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from config import Config
import logging
from logging.handlers import RotatingFileHandler
import time
import os

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s %(levelname)s %(message)s',
    datefmt='%Y-%m-%dT%H:%M:%SZ'
)
logging.Formatter.converter = time.gmtime  

db = SQLAlchemy()
login = LoginManager()
csrf = CSRFProtect()
limiter = Limiter(key_func=get_remote_address)

login.login_view = 'main.login'

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    # Generated By Copilot
    if not os.path.exists('logs'): 
        os.mkdir('logs')
    file_handler = RotatingFileHandler('logs/auth.log', maxBytes=1_000_000, backupCount=5)
    file_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s %(message)s',
        datefmt='%Y-%m-%dT%H:%M:%SZ'
    ))
    file_handler.setLevel(logging.INFO)
    app.logger.addHandler(file_handler)
    app.logger.setLevel(logging.INFO)
    app.logger.info('Application Startup')
    # Until Here

    db.init_app(app)
    csrf.init_app(app)
    login.init_app(app)
    limiter.init_app(app)

    login.login_view = 'main.login'
    login.session_protection = "strong"

    from .routes import main
    app.register_blueprint(main)

    from .models import User

    @login.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    return app