# Imported Necessary Libraries
import base64
import io
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
import pyotp
import qrcode
from app.models import User
from urllib.parse import urlparse
from flask_login import current_user, login_user, logout_user, login_required
from app import db, limiter
from app.forms import LoginForm, LogoutForm
from datetime import datetime, timedelta, timezone
import logging
import json

# Define Blueprint
main = Blueprint('main', __name__)

# Helper Function to Get Client IP
def getClientIp():
    return request.headers.get('X-Forwarded-For', request.remote_addr)

# Define Routes
@main.route('/')
def index():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    return redirect(url_for('main.login'))

# Login Rate Limiting
@limiter.limit("7 per minute")
@main.route('/login', methods=['GET', 'POST']) 
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    
    # Handle Login Form Submission
    form = LoginForm()
    showCaptcha = False
    
    # Process Form Submission
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user and user.lockedUntil:
            now = datetime.now(timezone.utc)
            if user.lockedUntil > now:
                timeRemaining = user.lockedUntil - now
                minutes = int(timeRemaining.total_seconds() / 60) 
                seconds = int(timeRemaining.total_seconds() % 60) 
                flash(f'Account Is Locked. Please Try Again In {minutes} Minutes And {seconds} Seconds.', 'danger')
                return redirect(url_for('main.login'))
            else:
                user.lockedUntil = None
                db.session.commit()
        
        # Show CAPTCHA After 3 Failed Attempts
        if user and user.failedAttempts >= 3 and user.failedAttempts < 5:
            showCaptcha = True
            if not showCaptcha:  
                logging.info(json.dumps({ # Json Dumps Generated By Copilot
                    "event": "captcha_trigger",
                    "username": user.username,
                    "clientIp": getClientIp(),
                    "failedAttempts": user.failedAttempts
                }))
            if form.recaptcha.errors:
                flash('Please Complete The CAPTCHA Verification Correctly.', 'warning')
                return render_template('login.html', title='Sign In', form=form, showCaptcha=showCaptcha)
        
        # Validate Username And Password
        if user is None or not user.checkPassword(form.password.data):
            logging.warning(json.dumps({ # Json Dumps Generated By Copilot
                "event": "password_failure",
                "username": form.username.data,
                "clientIp": getClientIp(),
                "userExists": user is not None
            }))
            
            if user:
                user.failedAttempts += 1
                
                if user.failedAttempts >= 5:
                    user.lockedUntil = datetime.now(timezone.utc) + timedelta(minutes=5)
                    user.failedAttempts = 0
                    logging.warning(json.dumps({ # Json Dumps Generated By Copilot
                        "event": "account_lockout",
                        "username": user.username,
                        "clientIp": getClientIp(),
                        "reason": "excessive_failed_attempts"
                    }))
                    flash('Too Many Failed Login Attempts. Account Locked For 5 Minutes.', 'danger')
                    db.session.commit()
                    return redirect(url_for('main.login'))
                
                db.session.commit()
            
            flash('Invalid Username Or Password', 'danger')
            return redirect(url_for('main.login'))
        
        # Successful Login
        user.failedAttempts = 0
        user.lockedUntil = None
        db.session.commit()
        
        # Handle MFA Redirection
        if user.mfaEnabled:
            session['pendingMfaUserId'] = user.id
            return redirect(url_for('main.mfaVerify'))
        elif not user.mfaSecret:
            session['pendingMfaUserId'] = user.id
            return redirect(url_for('main.mfaSetup'))
        
        session.clear()  
        login_user(user, remember=False, fresh=True)
        logging.info(json.dumps({ # Json Dumps Generated By Copilot
            "event": "login_success",
            "username": user.username,
            "clientIp": getClientIp(),
            "mfaEnabled": False
        }))
        nextPage = request.args.get('next')
        if not nextPage or urlparse(nextPage).netloc != '':
            nextPage = url_for('main.dashboard')
        return redirect(nextPage)
    
    # Show CAPTCHA If Needed On GET
    if request.method == 'GET' and form.username.data:
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.failedAttempts >= 3:
            showCaptcha = True
    
    return render_template('login.html', title='Sign In', form=form, showCaptcha=showCaptcha)

# MFA Setup Route
@main.route('/mfa/setup', methods=['GET', 'POST'])
def mfaSetup():
    from app.forms import MFAVerifyForm
    import qrcode
    from io import BytesIO
    import base64
    
    userId = session.get('pendingMfaUserId')
    if not userId:
        flash('Please Login First.', 'warning')
        return redirect(url_for('main.login'))
    
    user = User.query.get(userId)
    if not user:
        session.pop('pendingMfaUserId', None)
        return redirect(url_for('main.login'))
    
    if not user.mfaSecret:
        user.mfaSecret = pyotp.random_base32()
        db.session.commit()
    
    form = MFAVerifyForm()
    
    if form.validate_on_submit():
        totp = pyotp.TOTP(user.mfaSecret)
        if totp.verify(form.totpCode.data, valid_window=1):
            user.mfaEnabled = True
            db.session.commit()
            
            session.pop('pendingMfaUserId', None)
            session.clear()
            login_user(user, remember=False, fresh=True)
            
            logging.info(json.dumps({ # Json Dumps Generated By Copilot
                "event": "mfa_setup_success",
                "username": user.username,
                "clientIp": getClientIp()
            }))
            flash('MFA Has Been Successfully Enabled!', 'success')
            return redirect(url_for('main.dashboard'))
        else:
            logging.warning(json.dumps({ # Json Dumps Generated By Copilot
                "event": "invalid_totp",
                "context": "mfa_setup",
                "username": user.username,
                "clientIp": getClientIp()
            }))
            flash('Invalid Code. Please Try Again.', 'danger')
    
    totpUri = pyotp.totp.TOTP(user.mfaSecret).provisioning_uri(
        name=user.username,
        issuer_name="CSC2031 App"
    )
    
    qr = qrcode.make(totpUri)
    buffer = BytesIO()
    qr.save(buffer, format='PNG')
    qrB64 = base64.b64encode(buffer.getvalue()).decode()
    
    return render_template('mfa_setup.html', 
                         form=form,
                         qrCode=qrB64,
                         secret=user.mfaSecret)

# MFA Verification Route
@main.route('/mfa/verify', methods=['GET', 'POST'])
def mfaVerify():
    from app.forms import MFAVerifyForm
    
    userId = session.get('pendingMfaUserId')
    if not userId:
        flash('Please Login First.', 'warning')
        return redirect(url_for('main.login'))
    
    user = User.query.get(userId)
    if not user or not user.mfaEnabled:
        session.pop('pendingMfaUserId', None)
        return redirect(url_for('main.login'))
    
    form = MFAVerifyForm()
    
    if form.validate_on_submit():
        totp = pyotp.TOTP(user.mfaSecret)
        if totp.verify(form.totpCode.data, valid_window=1):
            session.pop('pendingMfaUserId', None)
            session.clear()
            login_user(user, remember=False, fresh=True)
            
            logging.info(json.dumps({ # Json Dumps Generated By Copilot
                "event": "login_success",
                "username": user.username,
                "clientIp": getClientIp(),
                "mfaEnabled": True
            }))
            flash('Login Successful!', 'success')
            return redirect(url_for('main.dashboard'))
        else:
            logging.warning(json.dumps({ # Json Dumps Generated By Copilot
                "event": "invalid_totp",
                "context": "mfa_verify",
                "username": user.username,
                "clientIp": getClientIp()
            }))
            flash('Invalid Authentication Code. Please Try Again.', 'danger')
    
    return render_template('mfa_verify.html', form=form, username=user.username)

# Dashboard Route
@main.route('/dashboard')
@login_required
def dashboard():
    logoutForm = LogoutForm()
    return render_template('dashboard.html', logoutForm=logoutForm)

# Logout Route
@main.route('/logout', methods=['POST'])
@login_required
def logout():
    logging.info(json.dumps({ # Json Dumps Generated By Copilot
        "event": "logout",
        "username": current_user.username,
        "clientIp": getClientIp()
    }))
    logout_user()
    session.clear()
    flash('You Have Been Logged Out.', 'info')
    return redirect(url_for('main.login'))

